
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button button2;
	private global::Gtk.Button button3;
	private global::Gtk.Label label1;
	private global::Gtk.Label lblFrequency;
	private global::Gtk.Label label4;
	private global::Gtk.Label label3;
	private global::Gtk.Label lblCPU;
	private global::Gtk.Label lblGPU;
	private global::Gtk.Label GtkLabel2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Tesla Coil Driver/Controller");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button ();
		this.button2.WidthRequest = 170;
		this.button2.HeightRequest = 70;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Coil ON");
		this.fixed1.Add (this.button2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button2]));
		w1.X = 46;
		w1.Y = 36;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button ();
		this.button3.WidthRequest = 170;
		this.button3.HeightRequest = 113;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Coil OFF");
		this.fixed1.Add (this.button3);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button3]));
		w2.X = 45;
		w2.Y = 127;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>ARM Frequency</b>");
		this.label1.UseMarkup = true;
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w3.X = 236;
		w3.Y = 41;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblFrequency = new global::Gtk.Label ();
		this.lblFrequency.WidthRequest = 135;
		this.lblFrequency.Name = "lblFrequency";
		this.lblFrequency.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
		this.fixed1.Add (this.lblFrequency);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblFrequency]));
		w4.X = 237;
		w4.Y = 67;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GPU Temp</b>");
		this.label4.UseMarkup = true;
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w5.X = 257;
		w5.Y = 186;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>CPU Temp</b>");
		this.label3.UseMarkup = true;
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w6.X = 257;
		w6.Y = 108;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblCPU = new global::Gtk.Label ();
		this.lblCPU.WidthRequest = 135;
		this.lblCPU.Name = "lblCPU";
		this.lblCPU.LabelProp = global::Mono.Unix.Catalog.GetString ("label5");
		this.fixed1.Add (this.lblCPU);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblCPU]));
		w7.X = 234;
		w7.Y = 134;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblGPU = new global::Gtk.Label ();
		this.lblGPU.WidthRequest = 135;
		this.lblGPU.Name = "lblGPU";
		this.lblGPU.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
		this.fixed1.Add (this.lblGPU);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblGPU]));
		w8.X = 234;
		w8.Y = 211;
		this.GtkAlignment.Add (this.fixed1);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Coil Controller</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel2;
		this.Add (this.frame1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 407;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
	}
}
